<section class="cms-blocks" data-bind="scope: 'cms-blocks-scope'">
    <button  class="get-cms-blocks-btn" type="button" data-bind="click: getStaticBlocks" id="get-cms-blocks-btn">
        <span data-bind="i18n: 'Get CMS blocks!'"></span>
    </button>
    <div class="cms-blocks-container">
        <table class="orders-container-table" id= "orders-container">
            <thead>
            <tr>
                <th data-bind="i18n: 'Cms block ID'"></th>
                <th data-bind="i18n: 'Cms block title'"></th>
            </tr>
            </thead>
            <tbody id="orders-table-body" data-bind="foreach: cmsBlocks()">
            <tr>
                <td data-bind="text: id"></td>
                <td data-bind="text: title"></td>
            </tr>
            </tbody>
        </table>
    </div>
</section>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                  "cms-blocks-scope": {
                    "component": "Magento_Cms/js/cms-blocks-output"
               }
            }
          }
        }
    }
</script>


