<div id="popup-content" class="popup-content" style="display:none">
   <?php
    echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('custom_block_title')
        ->toHtml();
    ?>
   <?php
   echo $this->getLayout()
       ->createBlock("Magento\Newsletter\Block\Subscribe")
       ->setTemplate("Magento_Newsletter::subscribe.phtml")
       ->toHtml();?>
</div>

<script type="text/x-magento-init">
    {
        "#popup-content": {
            "popup": {}
        }
    }
</script>
