<div class="items-container" data-bind="scope:'items-scope'">
    <div class="items-form-container">
        <form action="#" method="post" class="category-form">
            <label for="itemName">
                <span data-bind="i18n: 'Write item name!'"></span>
            </label>
            <input type="text" class="item-input" id="itemNameId" name="itemName">

            <label for="itemQty">
                <span data-bind="i18n: 'Write item quantity!'"></span>
            </label>
            <input type="text" class="item-input" id="itemQtyId" name="itemQty">

            <button class="get-items-btn" type="button" id="getItemsBtn" data-bind="click:getItems">
                <span data-bind="i18n: 'Get slider!'"></span>
            </button>
        </form>

    </div>

    <!-- ko if: productsImages().length > 0 -->
    <div data-bind=" foreach: productsImages(), mageInit: {'itemsSlider':{'sliderContainerSelector': '.products-slider'}}" class="products-slider">
            <div>
                 <img class="slider-image" data-bind="attr:{src: image.url, alt:name}" />
            </div>
        </div>
    <!-- /ko -->

    <!-- ko if: showNotification  -->
    <p> Unfortunately, there are no products match to this name. </p>
    <!-- /ko -->

</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                  "items-scope": {
                    "component": "Magento_Cms/js/items-category-output"
               }
            }
          }
        }
    }
</script>
