<?php
/** @var Magento\Framework\View\Element\Template $block */
?>

<p class="greet welcome text-welcome-name" data-bind="scope: 'customer'">
    <span
        data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().firstname)">
    </span>
</p>

<script type="text/x-magento-init">

    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
